#!/usr/bin/env bash
# config-toml.sh — Stage 4 composer for `<target>/.codex/config.toml`.
#
# Responsibilities:
#   1. Build the Sage managed block (paired markers START/END).
#   2. Inside the block: top-level developer_instructions, [features]
#      hooks=true, and [history] persistence.
#   3. v1: NO [[mcp_servers]] block (§8 deferred entirely).
#   4. Apply block-managed write strategy:
#      - Marker pair found  → replace content between markers.
#      - Marker pair absent → backup user file + regenerate.
#      - File absent        → write fresh.
#
# Entry point: compose_config_toml <target> <preset> <sage_framework>
#
# v1 spec ref: §4 Stage 4, §5 Tier B.
# v1 plan ref: T1.12.

CONFIG_TOML_START_MARKER='# >>> SAGE MANAGED BLOCK START'
CONFIG_TOML_END_MARKER='# <<< SAGE MANAGED BLOCK END'

# ------------------------------------------------------------------
# Managed block content
# ------------------------------------------------------------------

_build_managed_block() {
    cat <<EOF
${CONFIG_TOML_START_MARKER}
# Auto-generated by Sage. Regenerate with \`bin/sage update\`.
# Sage only refreshes content between the START / END markers.

developer_instructions = """
Sage hard kernel:
- State first: inspect .sage/work frontmatter and .sage/decisions.md before Standard+ work.
- Route work: use Sage workflows for action mandates; keep read-only questions conversational.
- Memory first: discover Sage Memory through the available Codex tool-discovery/MCP surface, then .sage-memory fallback when tools are unavailable.
- Bug reports/findings without an explicit fix mandate require capture/diagnosis first; do not edit code until the user asks for a fix or a workflow gate approves implementation.
- Artifacts before code: Standard+ work needs approved spec/plan and manifest scope before edits.
- Mutation boundary: source/runtime/test/config/instruction behavior changes require proper Sage workflow + approved scope; same-turn self-created artifacts are not approval.
- Polish prose: keep Sage artifact structure/canonical terms in English, but write new .sage prose in Polish, including append-only sections in older English files.
- Checkpoints: preserve [A] Review and [S] Skip review; after approved plan preserve [C] Checkpointed implementation and [F] Full autonomous implementation.
- Subagents/reviewers inherit the same Sage scope, project instructions, MCP/tool expectations, and verification gates.
- Verify: run tests and provide actual output before claiming done.
- Corrections: capture agent behavior learnings in .sage-memory when in approved scope.

AGENTS.md contains the compact project router; .agents/skills and core/workflows contain the method.
"""

[features]
hooks = true                  # required for L1 — confirms hooks loaded

# Optional review / model tuning (commented out by default; user-owned)
# review_model = "..."
# model_reasoning_effort = "medium"
# project_doc_max_bytes = 65536

# v1 ships NO [[mcp_servers]] block — MCP server deferred entirely
# (decision 2026-04-30, §2 / §8). Predicates run inline in bash hooks.
# When v2 triggers fire (§2 v2 promotion trigger), the regenerator
# adds a [[mcp_servers]] block here.

[history]
# 'persistence' is required by Codex 0.126.0-alpha.15 (rejects config
# without it). "save-all" matches Codex's default behaviour.
persistence = "save-all"
${CONFIG_TOML_END_MARKER}
EOF
}

# ------------------------------------------------------------------
# Post-compose repair and validation
# ------------------------------------------------------------------

_remove_legacy_postlude_features_fallback() {
    local target_file="$1"
    local tmp state
    tmp="$(mktemp)"
    state="$(mktemp)"

    awk -v end="${CONFIG_TOML_END_MARKER}" -v state="$state" '
        function trim(s) {
            sub(/^[[:space:]]+/, "", s)
            sub(/[[:space:]]+$/, "", s)
            return s
        }
        function flush_features(    i) {
            if (!in_features) return
            if (feature_codex == 1 && feature_other == 0) {
                removed = 1
            } else {
                for (i = 1; i <= feature_n; i++) print feature_buf[i]
            }
            delete feature_buf
            feature_n = 0
            feature_codex = 0
            feature_other = 0
            in_features = 0
        }
        before_end {
            print
            if ($0 == end) before_end = 0
            next
        }
        /^# <<< SAGE MANAGED BLOCK END$/ {
            print
            before_end = 0
            next
        }
        /^\[[^]]+\][[:space:]]*$/ {
            flush_features()
            if ($0 == "[features]") {
                in_features = 1
                feature_n = 1
                feature_buf[feature_n] = $0
                next
            }
            print
            next
        }
        in_features {
            feature_buf[++feature_n] = $0
            line = $0
            sub(/[[:space:]]*#.*/, "", line)
            line = trim(line)
            if (line == "") next
            if (line ~ /^codex_hooks[[:space:]]*=[[:space:]]*true[[:space:]]*$/) {
                feature_codex = 1
            } else {
                feature_other = 1
            }
            next
        }
        { print }
        END {
            flush_features()
            if (removed) print "removed" > state
        }
    ' before_end=1 "$target_file" > "$tmp"

    if grep -q '^removed$' "$state" 2>/dev/null; then
        mv "$tmp" "$target_file"
    else
        rm -f "$tmp"
    fi
    rm -f "$state"
}

_validate_singleton_toml_tables() {
    local target_file="$1"
    local duplicates
    duplicates="$(awk '
        /^\[features\][[:space:]]*$/ { features++ }
        /^\[history\][[:space:]]*$/ { history++ }
        END {
            if (features > 1) print "[features]"
            if (history > 1) print "[history]"
        }
    ' "$target_file")"

    if [ -n "$duplicates" ]; then
        local ts backup
        ts="$(date -u +%Y%m%dT%H%M%S)"
        backup="${target_file}.singleton-table-backup-${ts}"
        cp "$target_file" "$backup"
        printf 'generate-codex: duplicate singleton TOML table(s) after compose: %s\n' \
            "$(printf '%s' "$duplicates" | tr '\n' ' ')" >&2
        printf 'generate-codex: preserved config with user-owned duplicate data at %s\n' "$backup" >&2
        printf 'generate-codex: remove or migrate the user-owned duplicate table before rerunning stage 4.\n' >&2
        return 1
    fi

    if command -v python3 >/dev/null 2>&1 && \
       python3 -c 'import tomllib' >/dev/null 2>&1; then
        if ! python3 - "$target_file" <<'PY'
import pathlib
import sys
import tomllib

tomllib.loads(pathlib.Path(sys.argv[1]).read_text())
PY
        then
            printf 'generate-codex: strict TOML validation failed for %s\n' "$target_file" >&2
            return 1
        fi
    fi
}

# ------------------------------------------------------------------
# Block-managed write strategy
# ------------------------------------------------------------------

_write_with_block_strategy() {
    local target_file="$1"
    local managed_block="$2"

    if [ ! -f "$target_file" ]; then
        printf '%s\n' "$managed_block" > "$target_file"
        return 0
    fi

    # Detect both markers — pair must be present + ordered.
    local has_start has_end
    has_start=0
    has_end=0
    grep -q "^${CONFIG_TOML_START_MARKER}" "$target_file" && has_start=1
    grep -q "^${CONFIG_TOML_END_MARKER}"   "$target_file" && has_end=1

    if [ "$has_start" -eq 1 ] && [ "$has_end" -eq 1 ]; then
        # Replace content between markers; preserve outside verbatim.
        local pre post
        pre="$(awk -v s="${CONFIG_TOML_START_MARKER}" '$0 == s {exit} {print}' "$target_file")"
        post="$(awk -v e="${CONFIG_TOML_END_MARKER}" 'found {print} $0 == e {found=1}' "$target_file")"

        # Re-assemble: pre + new managed block + post.
        # Each piece may be empty; printf handles that gracefully.
        {
            [ -n "$pre" ] && printf '%s\n' "$pre"
            printf '%s\n' "$managed_block"
            [ -n "$post" ] && printf '%s\n' "$post"
        } > "$target_file"
        return 0
    fi

    # No marker pair → back up user file + regenerate fresh.
    local ts backup
    ts="$(date -u +%Y%m%dT%H%M%S)"
    backup="${target_file}.user-edit-backup-${ts}"
    cp "$target_file" "$backup"
    printf 'generate-codex: .codex/config.toml had no SAGE marker pair — saved your previous content to %s\n' "$backup" >&2
    printf '%s\n' "$managed_block" > "$target_file"
}

# ------------------------------------------------------------------
# Public entry point
# ------------------------------------------------------------------

compose_config_toml() {
    local target="$1"
    local _preset="$2"          # reserved (preset-specific tuning post-v1)
    local _sage_framework="$3"  # reserved
    : "$_preset" "$_sage_framework"

    mkdir -p "$target/.codex"

    local managed_block
    managed_block="$(_build_managed_block)"

    _write_with_block_strategy "$target/.codex/config.toml" "$managed_block"
    _remove_legacy_postlude_features_fallback "$target/.codex/config.toml"
    _validate_singleton_toml_tables "$target/.codex/config.toml" || return 1

    cat <<EOF
[stage 4] composed .codex/config.toml
  path=$target/.codex/config.toml
  managed_block=present (developer_instructions top-level, hooks=true, [history].persistence)
  mcp_servers=absent (v1 §8 deferred)
EOF
}
