#!/usr/bin/env bash
# config-toml.sh — Stage 4 composer for `<target>/.codex/config.toml`.
#
# Responsibilities:
#   1. Build the Sage managed block (paired markers START/END).
#   2. Inside the block: [features] codex_hooks=true + [history]
#      developer_instructions="""<rules digest>""".
#   3. v1: NO [[mcp_servers]] block (§8 deferred entirely).
#   4. Apply block-managed write strategy:
#      - Marker pair found  → replace content between markers.
#      - Marker pair absent → backup user file + regenerate.
#      - File absent        → write fresh.
#
# Entry point: compose_config_toml <target> <preset> <sage_framework>
#
# v1 spec ref: §4 Stage 4, §5 Tier B.
# v1 plan ref: T1.12.

CONFIG_TOML_START_MARKER='# >>> SAGE MANAGED BLOCK START'
CONFIG_TOML_END_MARKER='# <<< SAGE MANAGED BLOCK END'

# ------------------------------------------------------------------
# Managed block content
# ------------------------------------------------------------------

_build_managed_block() {
    cat <<EOF
${CONFIG_TOML_START_MARKER}
# Auto-generated by Sage. Regenerate with \`bin/sage update\`.
# Sage only refreshes content between the START / END markers.

[features]
codex_hooks = true            # required for L1 — confirms hooks loaded

# Optional review / model tuning (commented out by default; user-owned)
# review_model = "..."
# model_reasoning_effort = "medium"
# project_doc_max_bytes = 65536

# v1 ships NO [[mcp_servers]] block — MCP server deferred entirely
# (decision 2026-04-30, §2 / §8). Predicates run inline in bash hooks.
# When v2 triggers fire (§2 v2 promotion trigger), the regenerator
# adds a [[mcp_servers]] block here.

[history]
developer_instructions = """
Sage rules (loaded as developer instructions on every turn).
Authoritative reference: AGENTS.md in this project root.

Non-negotiable:
1. State First — scan .sage/work/ frontmatter and .sage/decisions.md
   before any substantial response.
2. Spec Before Code — Standard+ scope requires .sage/work/<id>/spec.md
   on disk before implementation.
3. Checkpoints — never skip approval gates; never change scope alone.
4. Verify — paste actual test output before claiming done.
5. Capture Corrections — store user corrections via self-learning.
6. Record Decisions — prepend to .sage/decisions.md at every checkpoint.

See AGENTS.md \"## Constitution\" section for the full ruleset.
"""
${CONFIG_TOML_END_MARKER}
EOF
}

# ------------------------------------------------------------------
# Block-managed write strategy
# ------------------------------------------------------------------

_write_with_block_strategy() {
    local target_file="$1"
    local managed_block="$2"

    if [ ! -f "$target_file" ]; then
        printf '%s\n' "$managed_block" > "$target_file"
        return 0
    fi

    # Detect both markers — pair must be present + ordered.
    local has_start has_end
    has_start=0
    has_end=0
    grep -q "^${CONFIG_TOML_START_MARKER}" "$target_file" && has_start=1
    grep -q "^${CONFIG_TOML_END_MARKER}"   "$target_file" && has_end=1

    if [ "$has_start" -eq 1 ] && [ "$has_end" -eq 1 ]; then
        # Replace content between markers; preserve outside verbatim.
        local pre post
        pre="$(awk -v s="${CONFIG_TOML_START_MARKER}" '$0 == s {exit} {print}' "$target_file")"
        post="$(awk -v e="${CONFIG_TOML_END_MARKER}" 'found {print} $0 == e {found=1}' "$target_file")"

        # Re-assemble: pre + new managed block + post.
        # Each piece may be empty; printf handles that gracefully.
        {
            [ -n "$pre" ] && printf '%s\n' "$pre"
            printf '%s\n' "$managed_block"
            [ -n "$post" ] && printf '%s\n' "$post"
        } > "$target_file"
        return 0
    fi

    # No marker pair → back up user file + regenerate fresh.
    local ts backup
    ts="$(date -u +%Y%m%dT%H%M%S)"
    backup="${target_file}.user-edit-backup-${ts}"
    cp "$target_file" "$backup"
    printf 'generate-codex: .codex/config.toml had no SAGE marker pair — saved your previous content to %s\n' "$backup" >&2
    printf '%s\n' "$managed_block" > "$target_file"
}

# ------------------------------------------------------------------
# Public entry point
# ------------------------------------------------------------------

compose_config_toml() {
    local target="$1"
    local _preset="$2"          # reserved (preset-specific tuning post-v1)
    local _sage_framework="$3"  # reserved
    : "$_preset" "$_sage_framework"

    mkdir -p "$target/.codex"

    local managed_block
    managed_block="$(_build_managed_block)"

    _write_with_block_strategy "$target/.codex/config.toml" "$managed_block"

    cat <<EOF
[stage 4] composed .codex/config.toml
  path=$target/.codex/config.toml
  managed_block=present (codex_hooks=true, [history].developer_instructions)
  mcp_servers=absent (v1 §8 deferred)
EOF
}
