#!/usr/bin/env python3
"""
Translate Sage legacy MCP JSON config into Codex-native config.toml.

Usage:
    python3 json_to_toml.py /path/to/project
    python3 json_to_toml.py --write /path/to/config.toml /path/to/project

Search order:
1. .claude/mcp.json
2. .sage/mcp.json

When writing into an existing Codex config, Sage preserves user-owned settings
outside the managed block and only refreshes translated MCP server entries.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from load_config import parse_codex_toml, split_dotted_key

SAGE_MANAGED_START = "# >>> SAGE MANAGED BLOCK START"
SAGE_MANAGED_END = "# <<< SAGE MANAGED BLOCK END"
LEGACY_HEADER = "# Auto-generated by Sage. Regenerate with `sage update`."


def is_bare_key(value: str) -> bool:
    return bool(re.fullmatch(r"[A-Za-z0-9_-]+", value))


def quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def format_key(value: str) -> str:
    return value if is_bare_key(value) else quote(value)


def render_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return quote(value)
    if isinstance(value, list):
        rendered = ", ".join(render_value(item) for item in value)
        return f"[{rendered}]"
    if isinstance(value, dict):
        rendered = ", ".join(
            f"{format_key(str(key))} = {render_value(item)}"
            for key, item in sorted(value.items())
        )
        return f"{{ {rendered} }}"
    return quote(str(value))


def emit_header(source: Path | None, project_root: Path, omitted_servers: list[str]) -> list[str]:
    lines = [
        SAGE_MANAGED_START,
        LEGACY_HEADER,
        "# Sage only refreshes this managed block. Keep user-owned Codex config",
        "# outside it and it will survive `sage update`.",
        "",
    ]
    if source:
        lines.append(f"# Translated from {source.relative_to(project_root)}")
    else:
        lines.append("# No legacy Sage MCP JSON found. This block can stay comment-only.")
    if omitted_servers:
        joined = ", ".join(omitted_servers)
        lines.append(f"# Preserved native mcp_servers entries already defined in config.toml: {joined}")
    lines.extend(
        [
            "",
            "# Codex already prefers AGENTS.override.md over AGENTS.md in each directory.",
            "# Uncomment these if your repo needs alternate instruction filenames or a larger budget:",
            '# project_doc_fallback_filenames = ["CLAUDE.md", ".agents.md"]',
            "# project_doc_max_bytes = 65536",
            "",
            "# Optional review / model tuning:",
            '# review_model = "gpt-5.4"',
            '# model_reasoning_effort = "medium"',
            '# model_verbosity = "medium"',
            '# web_search = "cached"',
            "",
            "# Optional workspace-write network access:",
            "# [sandbox_workspace_write]",
            "# network_access = true",
            "",
            "# Experimental hooks scaffold (.codex/hooks.json is loaded when enabled):",
            "# [features]",
            "# codex_hooks = true",
            "",
            "# Optional Codex-native skill toggles if you want per-skill overrides:",
            "# [[skills.config]]",
            '# path = ".agents/skills/example"',
            "# enabled = false",
            "",
        ]
    )
    return lines


def emit_server(name: str, config: dict) -> list[str]:
    lines = [f"[mcp_servers.{format_key(name)}]"]
    ordered_keys = [
        "command",
        "args",
        "cwd",
        "url",
        "env",
        "env_vars",
        "bearer_token_env_var",
        "http_headers",
        "env_http_headers",
        "enabled",
        "required",
        "startup_timeout_sec",
        "startup_timeout_ms",
        "tool_timeout_sec",
        "enabled_tools",
        "disabled_tools",
        "scopes",
        "oauth_resource",
        "experimental_environment",
    ]
    seen: set[str] = set()
    for key in ordered_keys + sorted(config.keys()):
        if key in seen or key not in config:
            continue
        seen.add(key)
        value = config[key]
        if value is None:
            continue
        lines.append(f"{format_key(key)} = {render_value(value)}")
    lines.append("")
    return lines


def load_legacy_config(project_root: Path) -> tuple[Path | None, dict]:
    for rel in (Path(".claude/mcp.json"), Path(".sage/mcp.json")):
        candidate = project_root / rel
        if candidate.is_file():
            with candidate.open("r", encoding="utf-8") as handle:
                parsed = json.load(handle)
            servers = parsed.get("mcpServers", parsed)
            if not isinstance(servers, dict):
                raise SystemExit(f"Unsupported MCP JSON shape in {candidate}")
            return candidate, servers
    return None, {}


def emit_managed_block(project_root: Path, skip_server_names: set[str] | None = None) -> str:
    skip_server_names = skip_server_names or set()
    source, servers = load_legacy_config(project_root)
    included_servers = {
        name: config
        for name, config in servers.items()
        if isinstance(config, dict) and name not in skip_server_names
    }
    omitted_servers = sorted(name for name in servers.keys() if name in skip_server_names)
    lines = emit_header(source, project_root, omitted_servers)
    for name, config in included_servers.items():
        lines.extend(emit_server(name, config))
    lines.append(SAGE_MANAGED_END)
    return "\n".join(lines).rstrip() + "\n"


def split_root_preamble(text: str) -> tuple[str, str]:
    lines = text.splitlines(keepends=True)
    for index, raw_line in enumerate(lines):
        stripped = raw_line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            return "".join(lines[:index]), "".join(lines[index:])
    return text, ""


def split_sections(text: str) -> tuple[str, list[str]]:
    preamble, remainder = split_root_preamble(text)
    if not remainder:
        return preamble, []
    lines = remainder.splitlines(keepends=True)
    sections: list[str] = []
    current: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            if current:
                sections.append("".join(current))
            current = [line]
        else:
            current.append(line)
    if current:
        sections.append("".join(current))
    return preamble, sections


def section_path(section: str) -> list[str]:
    first_line = section.splitlines()[0].strip()
    if not (first_line.startswith("[") and first_line.endswith("]")):
        return []
    return split_dotted_key(first_line[1:-1].strip())


def is_legacy_feature_section(section: str) -> bool:
    path = section_path(section)
    if path != ["features"]:
        return False
    lines = [
        line.strip()
        for line in section.splitlines()[1:]
        if line.strip() and not line.lstrip().startswith("#")
    ]
    return lines == ["codex_hooks = false"]


def strip_legacy_preamble(text: str) -> str:
    removable_prefixes = (
        LEGACY_HEADER,
        "# Translated from ",
        "# No legacy Sage MCP JSON found. Add Codex-native mcp_servers below.",
        "# Enable codex_hooks only after verifying your Codex version and",
        "# hook lifecycle needs. Sage treats hook parity as partial for now.",
    )
    lines = text.splitlines()
    kept = [
        line
        for line in lines
        if not any(line.startswith(prefix) for prefix in removable_prefixes)
    ]
    return "\n".join(kept).strip()


def strip_legacy_generated_content(text: str, managed_server_names: set[str]) -> str:
    preamble, sections = split_sections(text)
    kept_sections: list[str] = []
    for section in sections:
        path = section_path(section)
        if len(path) >= 2 and path[0] == "mcp_servers" and path[1] in managed_server_names:
            continue
        if is_legacy_feature_section(section):
            continue
        kept_sections.append(section.rstrip())

    cleaned_parts: list[str] = []
    cleaned_preamble = strip_legacy_preamble(preamble)
    if cleaned_preamble:
        cleaned_parts.append(cleaned_preamble)
    cleaned_parts.extend(section for section in kept_sections if section.strip())
    return "\n\n".join(cleaned_parts).strip()


def replace_managed_block(existing_text: str, managed_block: str) -> str:
    pattern = re.compile(
        rf"{re.escape(SAGE_MANAGED_START)}.*?{re.escape(SAGE_MANAGED_END)}\n?",
        re.DOTALL,
    )
    updated = pattern.sub(managed_block.rstrip() + "\n", existing_text, count=1)
    return updated.rstrip() + "\n"


def insert_managed_block(existing_text: str, managed_block: str) -> str:
    prefix, remainder = split_root_preamble(existing_text)
    pieces: list[str] = []
    if prefix.strip():
        pieces.append(prefix.rstrip())
    managed = managed_block.rstrip()
    if managed:
        pieces.append(managed)
    if remainder.strip():
        pieces.append(remainder.strip())
    return "\n\n".join(pieces).rstrip() + "\n"


def existing_server_names(path: Path) -> set[str]:
    try:
        parsed = parse_codex_toml(path)
    except Exception:
        return set()
    servers = parsed.get("mcpServers", {})
    if not isinstance(servers, dict):
        return set()
    return {str(name) for name in servers.keys()}


def write_config(target_path: Path, project_root: Path) -> None:
    source, servers = load_legacy_config(project_root)
    managed_server_names = {
        name for name, config in servers.items() if isinstance(config, dict)
    }

    if not target_path.exists():
        target_path.write_text(emit_managed_block(project_root), encoding="utf-8")
        return

    existing_text = target_path.read_text(encoding="utf-8")
    if SAGE_MANAGED_START in existing_text and SAGE_MANAGED_END in existing_text:
        target_path.write_text(
            replace_managed_block(existing_text, emit_managed_block(project_root)),
            encoding="utf-8",
        )
        return

    if LEGACY_HEADER in existing_text:
        cleaned = strip_legacy_generated_content(existing_text, managed_server_names)
        merged = insert_managed_block(cleaned, emit_managed_block(project_root))
        target_path.write_text(merged, encoding="utf-8")
        return

    if not source:
        return

    preserved_servers = existing_server_names(target_path)
    merged = insert_managed_block(
        existing_text,
        emit_managed_block(project_root, skip_server_names=preserved_servers),
    )
    target_path.write_text(merged, encoding="utf-8")


def main() -> int:
    argv = sys.argv[1:]
    if argv[:1] == ["--write"]:
        if len(argv) != 3:
            raise SystemExit("Usage: python3 json_to_toml.py --write /path/to/config.toml /path/to/project")
        target_path = Path(argv[1]).resolve()
        project_root = Path(argv[2]).resolve()
        write_config(target_path, project_root)
        return 0

    project_root = Path(argv[0] if argv else ".").resolve()
    sys.stdout.write(emit_managed_block(project_root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
