#!/usr/bin/env python3
"""
Translate Sage legacy MCP JSON config into Codex-native config.toml.

Usage:
    python3 json_to_toml.py /path/to/project

Search order:
1. .claude/mcp.json
2. .sage/mcp.json

If neither exists, emit a minimal Codex config with hooks disabled by default.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def emit_header() -> list[str]:
    return [
        "# Auto-generated by Sage. Regenerate with `sage update`.",
        "",
        "[features]",
        "codex_hooks = false",
        "",
        "# Enable codex_hooks only after verifying your Codex version and",
        "# hook lifecycle needs. Sage treats hook parity as partial for now.",
        "",
    ]


def emit_server(name: str, config: dict) -> list[str]:
    lines = [f"[mcp_servers.{name}]"]
    if "command" in config:
        lines.append(f"command = {quote(str(config['command']))}")
    if config.get("args") is not None:
        args = ", ".join(quote(str(arg)) for arg in config.get("args", []))
        lines.append(f"args = [{args}]")
    if config.get("cwd"):
        lines.append(f"cwd = {quote(str(config['cwd']))}")
    if config.get("url"):
        lines.append(f"url = {quote(str(config['url']))}")
    if config.get("env"):
        items = ", ".join(f"{key} = {quote(str(value))}" for key, value in sorted(config["env"].items()))
        lines.append(f"env = {{ {items} }}")
    if isinstance(config.get("enabled"), bool):
        lines.append(f"enabled = {'true' if config['enabled'] else 'false'}")
    if isinstance(config.get("required"), bool):
        lines.append(f"required = {'true' if config['required'] else 'false'}")
    if config.get("enabled_tools"):
        tools = ", ".join(quote(str(tool)) for tool in config["enabled_tools"])
        lines.append(f"enabled_tools = [{tools}]")
    if config.get("disabled_tools"):
        tools = ", ".join(quote(str(tool)) for tool in config["disabled_tools"])
        lines.append(f"disabled_tools = [{tools}]")
    lines.append("")
    return lines


def load_legacy_config(project_root: Path) -> tuple[Path | None, dict]:
    for rel in (Path(".claude/mcp.json"), Path(".sage/mcp.json")):
        candidate = project_root / rel
        if candidate.is_file():
            with candidate.open("r", encoding="utf-8") as handle:
                parsed = json.load(handle)
            servers = parsed.get("mcpServers", parsed)
            if not isinstance(servers, dict):
                raise SystemExit(f"Unsupported MCP JSON shape in {candidate}")
            return candidate, servers
    return None, {}


def main() -> int:
    project_root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    source, servers = load_legacy_config(project_root)
    lines = emit_header()
    if source:
        lines.append(f"# Translated from {source.relative_to(project_root)}")
        lines.append("")
    else:
        lines.append("# No legacy Sage MCP JSON found. Add Codex-native mcp_servers below.")
        lines.append("")
    for name, config in servers.items():
        if isinstance(config, dict):
            lines.extend(emit_server(name, config))
    sys.stdout.write("\n".join(lines).rstrip() + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
