#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# Sage → Codex Setup
# Generates AGENTS.md + .agents/skills + .codex/config.toml
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

SAGE_ROOT="${1:-.}"
SAGE_DIR="${SAGE_FRAMEWORK_DIR:-$SAGE_ROOT/sage}"
CODEX_DIR="$SAGE_ROOT/.codex"
AGENTS_DIR="$SAGE_ROOT/.agents"
PROJECT_SAGE="$SAGE_ROOT/.sage"
CORE="$SAGE_DIR/core"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "🚀 Sage → Codex Setup"
echo "═══════════════════════════════"

if [ ! -d "$CORE" ]; then
  echo "❌ Sage framework not found at $SAGE_DIR"
  echo "   Run this from the project root with Sage available locally."
  exit 1
fi

echo ""
echo "📁 Creating Codex structure..."
mkdir -p "$CODEX_DIR" "$AGENTS_DIR/skills"

echo "📝 Generating AGENTS.md..."
cat > "$SAGE_ROOT/AGENTS.md" << 'AGENTSEOF'
# Sage — Codex Instructions

> Auto-generated by Sage. Regenerate with `sage update`.

You are operating with the Sage framework inside Codex. Use Codex-native
instructions, Codex-native skills, and shared `.sage/` project state.

## Start Here

Before substantial work:

1. Read project state in `.sage/work/` and recent context in `.sage/decisions.md`.
2. For new or ambiguous tasks, start with the `sage` workflow skill.
3. For explicit workflows, activate the matching workflow skill in
   `.agents/skills/`.
4. For domain-specific execution, load only the relevant direct skill.

This preserves Sage's progressive disclosure model:
- metadata first
- `SKILL.md` when chosen
- references/scripts only when needed

For narrow directory-specific overrides, Codex also supports `AGENTS.override.md`.
Prefer keeping shared repository guidance in `AGENTS.md` and using overrides only
when a subtree genuinely needs different rules.

## Fast Entry in Codex

Codex supports two good discovery paths for Sage workflows:

- Type `$` in the composer to invoke a Sage skill directly.
- Type `/` to open the slash list; enabled Sage skills also appear there.

Use these entrypoints intentionally:

- `$sage` for ambiguous work or first-pass routing
- `$build` for feature work and implementation
- `$fix` for bug investigation and repair
- `$architect` for redesigns, migrations, and system planning
- `$continue` to resume an in-progress initiative
- `$status` to inspect current project state before deciding what to do
- `/review` for Codex-native diff review, and `$review` when the review itself
  is the Sage workflow

Short prompts that work well:

- `$sage help me route this request`
- `$build add usage analytics to onboarding`
- `$fix debug why the MCP manifest is empty`
- `/review this diff for regression risk`
- `$review review the generated spec before implementation`

## Process Constitution

### Rule 0: Route Every Substantial Request

For Standard+ tasks, route before implementation:

- build / create / implement / add / develop / ship → `build`
- fix / bug / broken / failing / error / debug → `fix`
- architect / redesign / migrate / rewrite → `architect`
- continue / resume / pick up → `continue`
- research / understand / interview / discover → `research`
- design / UX / PRD / wireframe / prototype → `design`
- analyze / audit / evaluate / assess → `analyze`
- review → `review`
- qa / smoke / browser test → `qa`
- reflect / retro / lessons → `reflect`

If routing is ambiguous, use `sage`, which routes through `sage-navigator`.

### Rule 1: State First

Do not start fresh if `.sage/` already contains context.

- Read `.sage/work/` frontmatter for active initiatives.
- Read `.sage/decisions.md` for recent reasoning.
- Resume from existing artifacts whenever possible.

### Rule 2: Skills Before Assumptions

If a Sage skill exists for the current task, use it instead of relying on
general model behavior.

Primary skill locations:
- `.agents/skills/<workflow>/SKILL.md`
- `.agents/skills/<direct-skill>/SKILL.md`

### Rule 3: Build Requires Spec and Plan

For Standard+ build work, both files must exist before implementation:

- `.sage/work/<initiative>/spec.md`
- `.sage/work/<initiative>/plan.md`

If either file is missing, create it first.

### Rule 4: Fix Requires Root Cause Before Change

For fix work:

1. identify root cause with evidence
2. scope the fix
3. only then implement

Systemic fixes should escalate to `build` or `architect`.

### Rule 5: Verify Before Claiming Done

Before calling work complete:

- run relevant tests/checks
- confirm behavior matches the request
- review the diff for regressions or risky patterns

Use Codex built-in `/review` for diff-oriented review when helpful.

### Rule 6: Keep Project State Shared

`.sage/` is the platform-agnostic state directory. Do not create Codex-only
state alternatives for specs, plans, decisions, or workflow progress.

## Workflow Entry

Use these Codex-native workflow skills:

- `.agents/skills/sage/`
- `.agents/skills/build/`
- `.agents/skills/fix/`
- `.agents/skills/architect/`
- `.agents/skills/continue/`
- `.agents/skills/review/`
- `.agents/skills/status/`

If the request is substantial and no explicit workflow is obvious, start with:

`Use $sage and route this task through the Sage workflow.`

If you want starter material for native Codex surfaces, look in the framework
under `runtime/platforms/codex/` (or `sage/runtime/platforms/codex/` in
standard projects):

- `AUTOMATIONS.md`
- `HOOKS.md`

## Subagents and Review

Codex supports multi-agent execution. When a Sage workflow expects an
independent classifier, reviewer, or QA pass, prefer a fresh agent/subagent
instead of self-approving in the same reasoning thread.

## MCP

Project-scoped Codex config lives in `.codex/config.toml`.

- If `mcp_servers` are configured there, use them natively.
- Sage may manage only a marked block inside `.codex/config.toml`; preserve
  unrelated user-owned Codex settings outside that block.
- Do not assume `.claude/mcp.json` is the primary configuration surface in
  Codex mode.

## Hooks

Treat Codex hooks as partial support. Do not assume Claude lifecycle parity
unless the project explicitly enables and configures Codex hooks.
AGENTSEOF

echo "📊 Checking project state..."
if [ ! -d "$PROJECT_SAGE" ]; then
  mkdir -p "$PROJECT_SAGE/docs" "$PROJECT_SAGE/work" "$PROJECT_SAGE/gates/scripts"

  cat > "$PROJECT_SAGE/decisions.md" << 'DECEOF'
# Decisions

Shared log for significant decisions and context.
Both the AI agent and human collaborators write here.

- [init] Sage initialized
DECEOF

  echo "  ✓ .sage/ initialized"
else
  mkdir -p "$PROJECT_SAGE/gates/scripts"
  echo "  ✓ .sage/ already exists"
fi

echo ""
echo "🔒 Deploying gate scripts..."
GATE_SCRIPTS="$CORE/gates/scripts"
if [ -d "$GATE_SCRIPTS" ]; then
  for script in "$GATE_SCRIPTS"/*.sh; do
    [ -f "$script" ] || continue
    cp "$script" "$PROJECT_SAGE/gates/scripts/"
    chmod +x "$PROJECT_SAGE/gates/scripts/$(basename "$script")"
    echo "  ✓ $(basename "$script")"
  done
fi

GATE_CONFIG="$CORE/gates/_config/gate-modes.yaml"
if [ -f "$GATE_CONFIG" ]; then
  cp "$GATE_CONFIG" "$PROJECT_SAGE/gates/gate-modes.yaml"
  echo "  ✓ gate-modes.yaml"
fi

echo ""
echo "🧭 Deploying sage-navigator..."
NAV_SRC="$CORE/capabilities/orchestration/sage-navigator"
NAV_DEST="$AGENTS_DIR/skills/sage-navigator"
if [ -f "$NAV_SRC/SKILL.md" ]; then
  rm -rf "$NAV_DEST"
  mkdir -p "$NAV_DEST"
  cp "$NAV_SRC/SKILL.md" "$NAV_DEST/SKILL.md"
  echo "  ✓ sage-navigator"
fi

workflow_description() {
  case "$1" in
    sage) echo "Primary Sage router. Start here for ambiguous tasks, then route into the right workflow." ;;
    build) echo "Feature implementation workflow. Use for new behavior, refactors, and planned delivery work." ;;
    fix) echo "Bugfix workflow. Use for regressions, breakages, and debugging with root-cause-first discipline." ;;
    architect) echo "Planning workflow for redesigns, migrations, and system-level decisions before implementation." ;;
    continue) echo "Resume an in-progress Sage initiative from existing briefs, specs, plans, and decisions." ;;
    review) echo "Independent Sage review workflow. Pair with Codex built-in /review for diff-heavy code review." ;;
    status) echo "Inspect current Sage project state, active initiatives, and what should happen next." ;;
    research) echo "Use for discovery, interviews, JTBD, and understanding before solutioning." ;;
    design) echo "Use for briefs, specs, UX definition, and product design work." ;;
    analyze) echo "Use for evaluation, audit, measurement, and findings against existing work." ;;
    qa) echo "Use for QA, smoke testing, and verification reporting." ;;
    reflect) echo "Use for retrospection, learnings, and seeding the next cycle." ;;
    learn) echo "Use for codebase scanning and turning findings into durable project knowledge." ;;
    map) echo "Use for dependency, ontology, and relationship mapping." ;;
    design-review) echo "Use for design quality review, slop detection, and design-system checks." ;;
    *) echo "Use when the task matches the Sage $1 workflow." ;;
  esac
}

echo ""
echo "⚡ Generating workflow skills..."
WF_COUNT=0
for wf_file in "$CORE"/workflows/*.workflow.md; do
  [ -f "$wf_file" ] || continue
  wf_name=$(basename "$wf_file" .workflow.md)
  wf_title=$(printf '%s' "$wf_name" | tr '-' ' ')
  wf_desc=$(workflow_description "$wf_name")
  wf_dest="$AGENTS_DIR/skills/$wf_name"

  rm -rf "$wf_dest"
  mkdir -p "$wf_dest"
  {
    echo "---"
    echo "name: $wf_name"
    echo "description: >-"
    echo "  $wf_desc"
    echo "---"
    echo ""
    echo "# Sage $wf_title workflow"
    echo ""
    echo "Codex-native workflow skill for Sage."
    echo ""
    if [ "$wf_name" = "review" ]; then
      echo "For code diffs and commit review, Codex built-in \`/review\` is useful."
      echo ""
    fi
    echo "Use shared project state in \`.sage/\` and avoid creating platform-specific"
    echo "state duplicates."
    echo ""
    sed '/^---$/,/^---$/d' "$wf_file"
  } > "$wf_dest/SKILL.md"

  WF_COUNT=$((WF_COUNT + 1))
  echo "  ✓ $wf_name"
done
echo "  → $WF_COUNT workflow skills"

echo ""
echo "📚 Copying direct skills..."
SK_COUNT=0
SK_REFRESH_COUNT=0
for skill_dir in "$SAGE_DIR"/skills/*/; do
  [ -d "$skill_dir" ] || continue
  skill_name=$(basename "$skill_dir")
  skill_dest="$AGENTS_DIR/skills/$skill_name"
  [ -f "$skill_dir/SKILL.md" ] || continue

  if grep -q "type: bundle" "$skill_dir/SKILL.md" 2>/dev/null; then
    continue
  fi

  if [ -d "$skill_dest" ]; then
    rm -rf "$skill_dest"
    SK_REFRESH_COUNT=$((SK_REFRESH_COUNT + 1))
    echo "  ↻ $skill_name"
  else
    echo "  ✓ $skill_name"
  fi

  mkdir -p "$skill_dest"
  cp "$skill_dir/SKILL.md" "$skill_dest/SKILL.md"
  for subdir in references templates examples patterns anti-patterns integration scripts resources constitution gates; do
    [ -d "$skill_dir/$subdir" ] && cp -a "$skill_dir/$subdir" "$skill_dest/"
  done

  SK_COUNT=$((SK_COUNT + 1))
done
echo "  → $SK_COUNT direct skills ($SK_REFRESH_COUNT refreshed)"

echo ""
echo "⚙️  Updating .codex/config.toml..."
python3 "$SCRIPT_DIR/../../../mcp/json_to_toml.py" --write "$CODEX_DIR/config.toml" "$SAGE_ROOT"
echo "  ✓ .codex/config.toml"

echo ""
echo "✅ Codex adapter ready"
echo "  AGENTS.md          → Codex always-on instructions"
echo "  .agents/skills/    → workflow + direct skills"
echo "  .codex/config.toml → Codex-native project config"
echo "  .sage/             → shared project state"
